# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eca1b3eeb94901ddc8167aede7fc0ba85b159f4079635b37a8c9cde6e40c3f155efcc7922310ff045c3a2d71072a8916e99db01afc8cbf9f851a72204ebb7c9

test:
  secret_key_base: 01bd7a99536690239409f9febe7e47f3ad1b8465c2c071a7e89c33b130843e6bd66088bc93e6f222613dc6910cd9f75f12217324c534fbe25ae7a61134d666b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
